### ISSUE TITLE
Compiling Flint 2.6.3 and ARB 2.18.1

### ISSUE THREAD

**Issue by duhadler** [BrianGladman/flint#1]
I have just downloaded the recent updates of your build system for Flint and Arb. It turns out that the following files are missing in flint: 

fmpz.c in \flint\fmpz
fft_tuning.h in \flint
fmpz-conversions.h   in \flint

Copying these files from your Flint 2.6.0 version made everyting compile, and all tests in Flint and Arb passed.
Thank you again for providing this build system and for keeping it current!

**Comment by BrianGladman** [comment]
Those three files are not supposed to be in the repository since they are generated when flint_config.py is run to create the Visual Studio build.   

Since they were missing it seems that something went wrong when you ran flint_config.py - I have just checked that this works for me so I am not able to say why they didn't get built for you.   

I would be grateful if you could double check this by deleting (or renaming) these three files and then running flint-config.py again to check that they are not being built.   If so, it means that flint_config.py is not working properly on your system for some reason.

**Comment by duhadler** [comment]
Thank you for your quick reponse!
Your are right - I had simply forgotten that I need to run flint_config.py first. Everything is working as it should.
